### ISSUE TITLE
Register link should be more visible

### ISSUE THREAD

**Issue by foobarable** [up2university/single-sign-on#5]

**Comment by foobarable** [comment]
Done in sso.test.up2university.eu, can be deployed to production

**Comment by michzimny** [comment]
Yes, it's better now.

By the way, there are some typos:
* in the SSO front page: "EduGAIN AAi" -> "EduGAIN AAI" (case)
* page "Register new account ...": "including a url" -> "including an url"

**Comment by 8c44klfls** [comment]
I close this issue now. Checked https://learn.test.up2university.eu/ and typos mentioned are gone.
<img width="580" alt="sso page" src="https://user-images.githubusercontent.com/39767077/41115111-cbaae3e8-6a86-11e8-93da-5f4d5a694067.png">

**Comment by michzimny** [comment]
For me it seems this one is still an issue:
> page "Register new account ...": "including a url" -> "including an url"

(this one can be found by clicking "register here")

and also in the landing page (the screenshot above) it's "EduGAIn" but it should be either EduGAIN or eduGAIN.

**Comment by athird** [comment]
@michzimny I can't bring up the page right now to check, but "including a url" is correct (since verbally, "URL" starts with a consonantal sound - You-arr-ell :-) ). Though the case should be corrected, it should be "URL".

**Comment by michzimny** [comment]
Yes, you're right of course :)

**Comment by michzimny** [comment]
@foobarable, could we have "EduGAIN" instead of "EduGAIn", and (minor, by the way) "URL" instead of "url"?

**Comment by athird** [comment]
@michzimny @foobarable Actually, I've been meaning to ask about "EduGAIN" - can we have a different word/phrase entirely? How many people know what EduGAIN is? Maybe something like "Login with your school/university account" instead.

**Comment by michzimny** [comment]
@athird has suggested "Login with your institution account via EduGAIN". I think it's better than the current wording. Could we please change it? And also the case as in my comments above. @foobarable ?
